# Generated by Django 5.1.3 on 2025-03-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='MCA', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_coordinator',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
